# Generated by Django 3.0 on 2022-07-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20220709_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='content',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
